name: Daily image build

on:
  schedule:
    - cron:  '0 5 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest

    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: on
      GOFLAGS: -ldflags=-s -ldflags=-w
      KO_DOCKER_REPO: ghcr.io/${{ github.repository }}
      KOCACHE: ~/ko

    steps:
    - uses: actions/checkout@v3
      with:
        path: ./src/github.com/tektoncd/chains

    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ${{ env.KOCACHE }}
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Build and push
      working-directory: ./src/github.com/tektoncd/chains
      timeout-minutes: 10
      run: |
        go install github.com/google/ko@latest
        ko build --sbom none --base-import-paths --tags ${{ github.sha }},latest ./cmd/controller
